<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecteurRepository extends EntityRepository
{

	public function findOne($id){
		  $qb = $this->createQueryBuilder('s');
		  $qb->where('s.id =:id')->setParameter('id',$id)->getQuery()->getSingleResult();
	}


  public function findSecteursAllByVille ($region=null){
  
       $qb = $this->createQueryBuilder('p');
        if($region!=null){
           $qb->where('p.ville=:ville')
          ->setParameter('ville', $region);
          }
         return $qb->getQuery()->getResult();    
      }
}
