
homepage:
    path:     /
    defaults: { _controller: "AppBundle:App:index" }
    methods:  GET
mobileapp:
    path:     /apk
    defaults: { _controller: "AppBundle:Mobile:apk" }
    methods:  GET

set_periode:
    path:     /set/periode
    defaults: { _controller: "AppBundle:App:setPeriode" }
    methods:  POST


user_homepage:
    path:     /v1/home
    defaults: { _controller: "AppBundle:Prospect:index" }
    methods:  GET


app_admin:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /v1

      
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"


fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile


fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register


fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting


fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


load_default_secteur:
    path:     /load/secteurs
    defaults: { _controller: "AppBundle:App:loadSecteurs" }
    methods:  GET

load__point_vente_from_excel:
    path:     /load/point/vente/from/excel
    defaults: { _controller: "AppBundle:App:loadPointVentesFromExcel" }
    methods:  GET

load__point_visite_excel:
    path:     /load/visite/from/excel
    defaults: { _controller: "AppBundle:Visite:loadVisitesFromExcel" }
    methods:  GET


load_default_quartier:
    path:     /load/quartiers
    defaults: { _controller: "AppBundle:App:loadQuartiers" }
    methods:  GET