save_prospects:
    path:      /save/prospects
    defaults: { _controller: "AppBundle:Mobile:saveProspects" }
    methods:  POST

create_token:
    path:      /create/auth-token
    defaults: { _controller: "AppBundle:Mobile:postAuthTokens" }
    methods:  POST

