visite_dernieres:
    path:     /{template}/dernieres/visite
    defaults: { _controller: "AppBundle:Visite:dernieresVisites",template:'all' }
    methods:  GET

visite_periodes:
    path:     /{template}/periodes/visite
    defaults: { _controller: "AppBundle:Visite:visitesPeriode",template:'all' }
    methods:  GET

visite_par_pdv_excel:
    path:     /pdv/excel
    defaults: { _controller: "AppBundle:Visite:derniereVisiteExcel" }
    methods:  GET

visites:
    path:     /
    defaults: { _controller: "AppBundle:Visite:visites" }
    methods:  GET
visites_excel:
    path:     /excel
    defaults: { _controller: "AppBundle:Visite:visitesExcel" }
    methods:  GET
visite_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Visite:show" }
    methods:  GET



