app_prospect:
    resource: "@AppBundle/Resources/config/routing/prospect.yml"
    prefix:   /prospect

app_mobile:
    resource: "@AppBundle/Resources/config/routing/mobile_routes.yml"
    prefix:   /mobile
